name: Node CI

on:
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
        npm run build
      env:
        CI: true
        TZ: Europe/Berlin
